<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Controller;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */




   
class DogRepository extends \Doctrine\ORM\EntityRepository 
{
	

	
}	