<?php

namespace AppBundle\Repository;

/**
 * IlikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IlikeRepository extends \Doctrine\ORM\EntityRepository
{
}
