<?php

namespace AppBundle\Repository;

/**
 * miPiaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class miPiaceRepository extends \Doctrine\ORM\EntityRepository
{
}
